[package]
name = "celestium"
version = "0.1.0"
authors = ["Jens Hegner Stærmose <jhs@artificialmind.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "celestium"
path = "src/lib.rs"

[dependencies]
rand = "0.6.5"
sha2 = "0.9.2"
rayon = "1.5.0"

[dependencies.secp256k1]
version = "0.19.0"
features = ["rand"]